version: "3.8"
services:
  localstack:
    container_name: fastify-lambda-localstack
    image: localstack/localstack:2.3.2
    ports:
      - "127.0.0.1:4566:4566"            
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./dist/function.zip:/opt/code/localstack/function.zip
      - ./setup.sh:/opt/code/localstack/setup.sh
    command: ["/bin/bash", "-c", "chmod u+x ./setup.sh"]
